# ---Utils---
[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.nvim']
on_path = '.*'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

# ---Completion---
# ==Common==
[[plugins]]                                                                       
repo = 'Shougo/deoplete.nvim'                                                     
if = 'has("nvim")'                                                                
hook_source = '''                                                                 
  let g:deoplete#enable_at_startup = 1                                            
  let g:deoplete#enable_ignore_case = 1                                           
  let g:deoplete#enable_smart_case = 1                                            
  let g:deoplete#omni#input_patterns = {}                                         
  let g:deoplete#omni#input_patterns.ruby =                                       
  \ ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::']                                           
  " <TAB>: completion.                                                            
  imap <expr><TAB> pumvisible() ? "\<C-N>" :                                      
  \ neosnippet#jumpable() ?                                                       
  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"                            
  smap <expr><TAB> neosnippet#jumpable() ?                                        
  \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"                            
  " <S-TAB>: completion back.                                                     
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"                    
'''

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# ==Ruby==
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_i = 1
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = 'ruby'

[[plugins]]
repo = 'thinca/vim-ref'
on_ft = 'ruby'
hook_source = '''
  let g:ref_refe_cmd = '/usr/local/bin/refe'
'''

# ==Python==
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
  autocmd FileType python setlocal completeopt-=preview
  letg:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_i = 1
on_ft = 'python'

# [[plugins]]
# repo = 'lambdalisue/vim-pyenv'
# depends = ['davidhalter/jedi-vim']
# on_ft = ['python','python3']
