# dein.toml
# Utils ====================
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/plugins/LanguageClient-neovim.rc.vim
'''

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/plugins/fugitive.rc.vim
'''
# Filer ====================
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.rc.vim
'''

# Word process =============
[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'
