# dein_lazy.toml
# complete ===============
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

# Snippet =================
[[plugins]]
repo = 'Shougo/neosnippet'
on_i  = 1
depends = ['neosnippet-snippets']
hook_source = '''
source ~/.config/nvim/plugins/neosnippets.rc.vim
'''
hook_add = '''
let g:neosnippet#snippets_directory = "$XDG_CONFIG_HOME/nvim/autoload/snippets/"
'''
