# dein.toml
# Utils ====================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/plugins/fugitive.rc.vim
'''
# Filer ====================
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.rc.vim
'''

# Word process =============
[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

# Checker ==================
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.config/nvim/plugins/ale.rc.vim
'''

# Snippets =================
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
